### ISSUE TITLE
 three analytic metrics (ACL, NCC, RPA)

### ISSUE THREAD

**Issue by bloom1-afk** [FarimaFatahi/CompactIE#2]
Hello author, can you tell us how to achieve These Three Analytic Metrics (ACL, NCC, RPA)?

**Comment by FarimaFatahi** [comment]
Hello, I updated the ReaeME inside the data/ folder to address this issue.

**Comment by bloom1-afk** [comment]
> Hello, I updated the ReaeME inside the data/ folder to address this issue.

I see it, thank you so much!
